[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
stake_program = "Gg5p4qsRXpneeSSiLUces9sMM3F3wp5AArGR9RnSrDky"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/relipa/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
